csm_web/frontend/src/components/Attendance.js, csm_web/scheduler/views.py
Sorts attendances so that most recent weeks are on top, and also filters Mentor profiles that have None sections on the API (I believe this caused a few 500s earlier in the semester).
=> Small QOL/resilience fixes

csm_web/scheduler/serializers.py, csm_web/scheduler/tests/test_api.py, csm_web/scheduler/views.py
Here's an endpoint that lets you edit spacetimes. I wasn't able to test it manually because I ran into some CSRF problems I didn't have time to figure out, so I wrote a test case instead.
A couple other things I noticed while making this:
- Our tests definitely have race conditions somewhere. After deleting the `test_enroll_drop` to see if the other tests passed, some runs would give 4 failures and others 3 without any changes occurring in between.
- DRF's @action annotation allows GET methods by default ("The action decorator will route GET requests by default, but may also accept other HTTP methods by setting the methods argument." https://www.django-rest-framework.org/api-guide/viewsets/#marking-extra-actions-for-routing). Visiting `/spacetimes/:pk/modify/` or …
=> Add endpoint for spacetime editing

csm_web/csm_web/settings.py, csm_web/scheduler/models.py, csm_web/scheduler/views.py, requirements.txt
The `/courses/$pk/sections` endpoint was *painfully* slow for courses with more than a handful of sections (taking 2-3 seconds to respond in production). I've optimized this to make it 2-3 times faster on average by making more intelligent use of the database. The increased efficiency should not only help reduce server strain during enrollment as this is easily our heaviest endpoint, but also improves QOL for coordinators as they access this endpoint regularly.
=> Performance enhancements for /courses/$pk/sections endpoint

csm_web/scheduler/management/commands/patchattendances.py
I want to run `manage.py patchattendances` every hour so that we stop getting questions from confused mentors about the roster/attendance mismatch, but the previous implementation was so inefficient in the number of database queries it performed and the locks it held I didn't feel comfortable running it during the day while people were using the application. This PR fixes that.
=> Efficient patchattendances

csm_web/frontend/src/components/Course.js, csm_web/frontend/src/components/CourseMenu.js
I realized there was an unnecessary 'waterfall' where when you navigated _directly_ to the course enrollment/management page (either by clicking a "coordinator" card or refreshing the enrollment page as a student) causing users to wait for two roundtrips to the API for requests that could be made in parallel.
=> Halve latency on direct navigation to course enrollment/management

csm_web/frontend/src/components/MentorSection.js, csm_web/frontend/src/utils/types.js
Implements one of the changes in #164. I tested this in both 24-hr and 12-hr display in both Chrome and Safari, so hopefully it works.
I noticed that the definition of `SPACETIME_SHAPE` seems to have a lot of fields missing - is this supposed to be the case, or are the fields just initialized late? If the former is the case then I'll fix the fields in this PR as well.
=> Autofill spacetime on override modal

README.md, csm_web/scheduler/tests/test_api.py, csm_web/scheduler/tests/test_enroll_drop.py, csm_web/scheduler/tests/test_management.py, csm_web/scheduler/tests/test_models.py, csm_web/scheduler/tests/utils.py
This PR fixes our test cases! Except for the spacetime/override ones, which I've commented out pending any new API changes to accommodate multiple spacetimes.
Next steps after aforementioned API changes:
- Test cases for enrollment management scripts (I disabled tests for most of our commands as well, since those depend on the shape of attendance)
- Test cases in CI, at last
=> Fix test cases

csm_web/frontend/src/components/MentorSection.js, csm_web/frontend/src/components/StudentSection.js, csm_web/scheduler/factories.py, csm_web/scheduler/models.py, csm_web/scheduler/serializers.py, csm_web/scheduler/tests/test_models.py
Attendance now generated correctly for sections that meet more than once-per-week.
There is a quirk, consider this example: if a student drops a section that met on **Monday**  after attending it for the first time, and then signs up for a different section in the same course that meets on **Wednesday**, **both** attendances will be shown to the mentor of the latter section (i.e. the section the student is now enrolled in) despite the fact their section doesn't meet on Mondays. While this might be potentially confusing to Mentors (and possibly should be remedied on the frontend later on), I think this is the correct thing to do on the backend, as we want to know if a student didn't attend their initial section for the sake of P/NP or banning them if it was the first week of sections. …
=> Multiple sections attendance fix

csm_web/scheduler/management/commands/normalize_attendances.py
Stopgap solution until I think of something better, reduces mentor confusion by normalizing attendances such that they fall on the correct day of the week with respect to the section's spacetimes, even if students swapped in from a different section in the same course.
=> Add normalize_attendances management command

csm_web/frontend/src/components/resource_aggregation/ResourceTable.tsx, csm_web/frontend/src/components/resource_aggregation/Resources.tsx, csm_web/frontend/src/utils/user.tsx
Added a cache for resource data to reduce the number of API calls made while switching tabs. The cache updates when new changes are submitted to the database, and data is retrieved from the cache if present.
Also refactored the roles function and how we retrieve role information to reduce the number of API calls, storing all role information on first page load instead of retrieving them every time the user switches tabs (as user privileges are unlikely to change in one session; refreshing the page to update privilege information is natural).
=> Resource Caches

csm_web/frontend/src/components/App.js
Fixed active class matching for the navbar—the "Scheduler" link should always be active, unless the path is prefixed by `/resources`.
=> Navbar fixes

csm_web/frontend/static/frontend/css/resource_aggregation.css
Small one-line fix for longer names in resource tabs; they were overflowing for EECS16A and EECS16B.
However, the fix was to remove the fixed width of the tabs, which means that the wrapping for smaller screens (ex. mobile) is not as nice:
=> Fix resource tab CSS for longer names

csm_web/frontend/src/components/resource_aggregation/ResourceTable.tsx
Hotfix to fix the edit modal for a new resource if it is the first resource to be created—it used to error because of an undefined "last" resource.
=> Fix add new resource if no resources present

csm_web/frontend/src/components/Course.js, csm_web/frontend/src/components/MentorSection.js
Removed previous TODO comments and implemented section cards for online/in-person sections, and enabled a choice of online/in-person locations.
=> Modify frontend to give choice of virtual/in-person locations

csm_web/frontend/src/components/Home.js, csm_web/scheduler/serializers.py
Fixes #192.
Small frontend change to fix errors caused by coordinators also mentoring a section.
Also made a minor change to the backend `Section` serializer to give the coordinator full coord privileges to the section they're mentoring.
=> Allow coords to also mentor a section

csm_web/frontend/src/components/MentorSection.js, csm_web/frontend/static/frontend/css/style.css
The meta card previously did not appear in the mentor view, meaning that mentors can't view descriptions or capacities. This is now changed, and the meta card can now be viewed by mentors, while editing privileges are still restricted to coordinators.
Some other small changes were made to the arrangement of the section info cards in the section view—the students list now takes its own space on the left, while the other cards flex-flow on the right. This means that it's a lot easier to see the rest of the cards, and we don't have any cards that end up hiding below the student list after wrapping.
=> Add mentor meta card

csm_web/frontend/src/components/Course.tsx, csm_web/frontend/static/frontend/css/style.css
Modified the section view for both coordinators and students (they share the same component) to have sections in a grid below the day selection:
=> Restyle section view to have section cards in a grid

setup.sh
Currently, the `setup.sh` script adds the contents of `.env` to the virtual environment `activate` script, so that the environment variables are set whenever the user starts the virtual environment.
However, if the user decides to modify the `.env` file in any way, none of these changes are reflected in the `activate` script, and as such none of the new changes will be reflected in the environment variables.
A better way to do this would be to not duplicate the environment variables, and instead just source the `.env` file directly. To alleviate the need to prepend `export` to every line, we can also use `set -a` to make every `KEY=VALUE` pair be exported. This option is then reverted after we source the `.env` file with `set +a`.
=> Modify how the setup script sources .env

csm_web/frontend/src/components/CourseMenu.tsx, csm_web/frontend/src/components/course/Course.tsx, csm_web/frontend/src/components/course/SectionCard.tsx, csm_web/frontend/static/frontend/css/style.css, csm_web/scheduler/serializers.py, csm_web/scheduler/views/section.py
Resolves #257.
This PR
* Refactors the course menu to allow anybody to view sections for any course at any time
* Reworks the section cards to disable enroll buttons before the course is open
* Fixes bug in enrollment time display if priority enrollment is after normal course enrollment
* Adds status on course pages to show enrollment time for the specific course
=> Allow students to view sections prior to enrollment

csm_web/frontend/src/components/enrollment_automation/calendar/Calendar.tsx, csm_web/frontend/static/frontend/css/calendar.css, csm_web/scheduler/utils/match_solver.py
Resizing the window and scrolling the calendar sometimes causes the events to disappear. Hopefully this fixes the bug.
Also, removed a debug print statement from the matcher function.
=> Fix calendar resize event bug

csm_web/scheduler/views/section.py
Sentry issue: https://sentry.io/share/issue/9cc6519093e3485cb1cfb7bd6e419c80/
When creating a new section, if the first mentor in the mentor set of a course has no section, the request fails, since it fetches the duration from an existing section.
To fix this issue, an additional filter is made prior to fetching a previous section, so ensure that we're never getting a null section. Further, the duration default is set to one hour, in case no sections have been created yet.
Future improvement would be to add a field for duration when creating sections.
=> Add filter to course mentor set when creating sections

csm_web/frontend/src/components/Tooltip.tsx, csm_web/frontend/src/components/enrollment_automation/coordinator/CreateStage.tsx, csm_web/frontend/static/frontend/css/enrollment_matcher.css
Previous changes for the matcher feature had a bug with tooltips not showing in the create stage. Root of the issue was a missing parent element with `position: relative`; this is fixed in this PR, and additional documentation is added to the tooltip class as an attempt to prevent this in the future. Further, since a click activation for the tooltip would require event listeners and further design, this PR removes that feature, as it's not currently being used.
I've looked into modifying the tooltip component so that it doesn't need to be surrounded by a parent with `position: relative`, but this breaks the tooltips if used in the calendar—the event details are surrounded with a div with `overflow: hidden`, which would prevent the tooltips from showing. Circumventing this would require …
=> Fix matcher create stage tooltip, add tooltip jsdoc

csm_web/frontend/src/components/enrollment_automation/MentorSectionPreferences.tsx
Resolves #318.
Modified the frontend form submission to clamp the mentor preferences between 0 and `MAX_PREFERENCE`. There isn't really any good way to validate this value in the backend, as we want to be agnostic to different preference values, and having two places to change this setting will just allow more bugs in the future, but this could be redesigned/thought about later.
=> Add matcher mentor preference validation

csm_web/frontend/src/components/enrollment_automation/coordinator/ReleaseStage.tsx, csm_web/scheduler/views/matcher.py
Resolves #309.
Modified the frontend to filter out empty emails (after trimming) before sending the request; doesn't send the request if this filter removes all emails.
Additionally, modified the backend to skip over any invalid emails (i.e. emails that do not contain `@`, or any blank emails). This serves as an additional net to catch anything that slips through from the frontend.
=> Add validation when adding mentor emails

csm_web/frontend/src/components/Policies.tsx
No more errors about `ul` being descendent of `p`! 
closes #335
=> fixed <ul> cannot appear as a descendant of <p> error

csm_web/frontend/src/components/enrollment_automation/MentorSectionPreferences.tsx, csm_web/frontend/src/components/enrollment_automation/coordinator/CoordinatorMatcherForm.tsx, csm_web/frontend/src/components/enrollment_automation/coordinator/CreateStage.tsx, csm_web/frontend/src/components/enrollment_automation/coordinator/ReleaseStage.tsx, csm_web/frontend/static/frontend/css/enrollment_matcher.css, csm_web/scheduler/views/matcher.py
Resolves #308.
Reorganized matcher stages to move opening the matcher to the Release stage. This means that coordinators can add and edit mentor lists before opening the matcher.
Also modified the API endpoint for active matcher courses, omitting courses for mentors if the matcher is closed. This prevents the leak of information in the time period before mentors get their application decisions and after coordinators set up the scheduler for matcher preference submission.
=> Reorganize matcher stages, mentor matcher visibility

csm_web/csm_web/settings.py, package-lock.json, package.json, webpack.config.js
Bumps [nth-check](https://github.com/fb55/nth-check) to 2.1.1 and updates ancestor dependency [@svgr/webpack](https://github.com/gregberge/svgr). These dependencies need to be updated together.
Updates `nth-check` from 1.0.2 to 2.1.1
- [Release notes](https://github.com/fb55/nth-check/releases)
- [Commits](https://github.com/fb55/nth-check/compare/v1.0.2...v2.1.1)
Updates `@svgr/webpack` from 5.5.0 to 6.5.1
- [Release notes](https://github.com/gregberge/svgr/releases)
- [Changelog](https://github.com/gregberge/svgr/blob/main/CHANGELOG.md)
- [Commits](https://github.com/gregberge/svgr/compare/v5.5.0...v6.5.1)
---
updated-dependencies:
- dependency-name: nth-check dependency-type: indirect
- dependency-name: "@svgr/webpack" dependency-type: direct:development ...
Signed-off-by: …
=> Bump nth-check and @svgr/webpack

Procfile, release.sh
Modified the `Procfile` for Heroku to automatically migrate the postgres database after a release.
This can be expanded and added to further if more tasks are required in the future.
=> Add heroku release phase for database migration

cypress/e2e/course/coordinator-course.cy.ts, cypress/e2e/course/restricted-courses.cy.ts, cypress/e2e/section/coordinator-section.cy.ts, cypress/e2e/section/mentor-section.cy.ts
See https://docs.cypress.io/guides/core-concepts/retry-ability#Only-queries-are-retried.
Existing tests have used `.click().should(...)` to assert for changes after an action, which does not retry the assertion; this means that the corresponding tests are very flaky, especially when state changes across several re-renderings.
=> Refactor cypress tests to fix retryability flaking

csm_web/scheduler/admin.py
Quick PR for a fix to adding courses through the admin menu; it's currently broken on prod, but not an urgent issue (hence not a hotfix), though a timely merge would be beneficial.
Additionally, word of the day has been added to the admin menu, so we can view and edit individual word of the days for section occurrences.
=> Fix restricted courses admin, add word of the day to admin

csm_web/frontend/src/components/section/MentorSectionAttendance.tsx, csm_web/scheduler/management/commands/create_attendances.py, csm_web/scheduler/views/course.py, csm_web/scheduler/views/section.py
This is a PR for several hotfixes for the prod release of CS70 sections:
* There was an existing frontend issue that does not allow users to view attendances if no attendances exist.
* Additionally, some minor adjustments were made to attendance creation commands/views for edge cases.
* The courses endpoint was extremely slow, retrieving a query of over 5 million objects (before the `.distinct()` modifier) when really only around 7 courses are possible. This was optimized and rewritten with more queries but for fewer objects.
=> Hotfix: Errors when no attendances, Optimize courses endpoint

csm_web/frontend/src/components/enrollment_automation/MentorSectionPreferences.tsx, csm_web/frontend/src/utils/queries/matcher.tsx, csm_web/frontend/static/frontend/css/enrollment_matcher.css, csm_web/scheduler/views/matcher.py
Resolves #333.
Fixes the matcher exploit by posing a hard restriction on the number of nonzero preferences a mentor can submit. Currently, this is a hard-coded limit of 3 slots, but in the future, this should be configurable by the coordinator.
=> Prevent mentors from submitting less than 3 nonzero preferences

csm_web/scheduler/factories.py, csm_web/scheduler/tests/utils.py
Currently, running `createtestdata` takes about a minute to finish, which is quite a long time to wait when not very many objects are being created.
Some optimizations that have been made:
- Use `Factory.build` as much as possible, rather than using `Factory.create`, so that we can save all the instances at once with `bulk_create`. This requires a bit of shuffling around to get dependencies created correctly, especially since running `bulk_create` does not create related objects (ex. foreign key instances created by subfactories).
- Use `select_related` and `prefetch_related` in loops after creation, to avoid large amounts of queries in loops.
Additionally, the `factories.py` file has been reformatted along with these changes. In the future, we can do similar kinds of optimizations (as …
=> Optimize test data creation

csm_web/scheduler/management/commands/export_attendances.py
The current `export_attendances` command uses an old version of the attendance model, without section occurrences. It also had an issue where exported attendances would be duplicated (due to an inner join in selecting spacetime objects for ordering), and this has been fixed as well. The file was also reformatted via `black`.
=> Fix export attendance script

package-lock.json, package.json, requirements.txt
Dependabot automatic PRs tend to fail CIs because of insufficient secret access, so this PR will aggregate several pending dependabot updates.
Dependabot PRs aggregated:
* #355 
* #362 
* #365 
* #386 
* #387 
* #388
* #392
* #403
* #405
* #409
* #410
* #414
* #416
Additionally, a manual upgrade of `urllib3` from `1.26.6` to `1.26.11` was done due to dependency conflicts.
=> Update dependencies from dependabot

.github/workflows/cypress.yml, .github/workflows/django.yml, .github/workflows/nodejs.yml, .github/workflows/pre-commit.yml
Since the current GitHub actions are triggered by push and PR events on the master branch, any PRs or pushes to other branches do not trigger any workflows, and also cannot be manually triggered either. In case we'd like to run any CI actions on these extraneous branches, adding the `workflow_dispatch` trigger can be helpful, as it allows us to manually trigger workflows from the Actions tab: https://docs.github.com/en/actions/using-workflows/manually-running-a-workflow.
=> Add `workflow_dispatch` trigger to all actions

csm_web/frontend/urls.py, csm_web/scheduler/admin.py
Fixes #364, fixes #384.
The admin pages are all very outdated, and this PR does a lot of refactoring to make the lists more helpful, and fix a lot of legacy code (especially regarding permissions).
This PR also fixes some URL issues when trying to navigate to the admin page. In particular, the existing URL configuration to route to the frontend wasn't optimal; there was a hard-coded check that the URL does not begin with `api/`. This was changed to two routes; one routing from `/` to the frontend, and one routing any path `^.*/$` to the frontend.
The root cause for #364 turns out to be how Django handles URL matching. Since Django automatically adds a trailing slash if a path matches nothing, it is important that _all_ routes end with `/`, so that paths that do not end in a slash get …
=> Refactor admin pages

csm_web/frontend/src/components/section/SpacetimeEditModal.tsx
See #439 for the original fix of the issue, but after merging in #429, there were additional errors due to the types used in the form (the state change failed to convert a string to an int type). This is a follow-up PR fixing that issue as well.
=> Fix section day change form

cypress/e2e/course/coordinator-course.cy.ts
Small fix for replacing spaces in datetime strings, as currently a test fails because Cypress is unable to find the correct matches to check against.
=> Fix regex for Cypress datetime parsing

.github/workflows/pre-commit.yml, .pre-commit-config.yaml
With the changes in #457, `psycopg2-binary` is no longer installed by default in development systems (it causes a lot of setup issues). However, `pylint_django` requires a working Django backend in order to provide linting, which now errors due to a lack of the `psycopg2` package.
This PR modifies the pre-commit configuration to run `pylint` in Docker instead, as the Docker container has all of the backend dependencies installed. The pre-commit configuration also still had the old `--with=dev` flag, which is now swapped to `--with=prod`.
=> Fix pylint/pre-commit configuration

csm_web/frontend/src/components/course/CreateSectionModal.tsx, csm_web/frontend/src/components/section/MetaEditModal.tsx, csm_web/frontend/src/components/section/SpacetimeEditModal.tsx, csm_web/frontend/src/css/course.scss, csm_web/frontend/src/css/spacetime-edit.scss, csm_web/frontend/src/utils/queries/sections.tsx, csm_web/scheduler/views/section.py
Resolves #441
The section creation form and the override creation form have been causing several errors in the backend, since there is no input validation in the frontend. These forms have now been updated to provide input validation, displayed to the user upon clicking the save/submit button.
=> Add additional validation to various forms

csm_web/frontend/src/components/App.tsx, csm_web/frontend/src/components/enrollment_automation/coordinator/ReleaseStage.tsx, csm_web/frontend/src/css/base/base.scss, csm_web/frontend/src/css/header.scss, csm_web/frontend/src/css/section.scss
Some icons that are not filled were incorrectly filled in by the prior SCSS transition; this should be fixed now through the addition of a new `outline` class for icons, which sets the fill to none.
=> Fix outlined icons

csm_web/frontend/src/components/enrollment_automation/MentorSectionPreferences.tsx, csm_web/frontend/src/components/enrollment_automation/coordinator/ConfigureStage.tsx, csm_web/frontend/src/components/enrollment_automation/coordinator/CoordinatorMatcherForm.tsx, csm_web/frontend/src/components/enrollment_automation/coordinator/CreateStage.tsx, csm_web/frontend/src/components/enrollment_automation/coordinator/EditStage.tsx, csm_web/frontend/src/components/enrollment_automation/coordinator/ReleaseStage.tsx, csm_web/frontend/src/css/base/form.scss, csm_web/frontend/src/css/enrollment_matcher.scss
This PR makes various miscellaneous improvements to the matcher UI.
Coordinators have created slots without knowing that many slots are actually linked; a confirmation modal has been added because of this, listing out all of the slots along with a count of the number of slots to submit.
Another confirmation modal was added to the button opening the preference form for mentors, making it clear that slots cannot be edited afterward. This can probably be reverted or changed if in the future we decide to rework the slot creation system to allow for slot edits.
The create stage button UI/UX was also modified; to avoid any confusion with save/submit/continue buttons, the flows were reworked to have only one green (primary) button visible at any given point in time. Clicking this button would …
=> Restyle matcher UI

package-lock.json, package.json
Currently CI tests have been failing due to changes in Firefox, which should be fixed in the latest version of Cypress.
=> Update Cypress version

csm_web/scheduler/factories.py
Previously, the `createtestdata` script creates models in a fixed deterministic order, and almost always the mentor and section ids match up. This can cause some confusions during development, since it's hard to tell which ids correspond to mentors and which correspond to sections. This PR randomly shuffles all of the models prior to creation, to randomize the ids.
Further, all of the sections have very few mentors, and all courses have very few sections. This makes it quite hard to test query and frontend efficiency for larger courses and larger sections. This PR adds a few additional courses, with various combinations of many sections vs. many students per section.
=> Improvements to `createtestdata` script

docker-compose.yml
Currently, running `docker compose exec django makemigrations` will error, since the Django file system in Docker is read-only. This PR modifies the bind mounts to allow writes to the migrations folder. (The migrations folder in the frontend app is not included here, since we only make database changes within the `scheduler` app.)
=> Update docker-compose to allow migrations to be created in Docker

setup.sh
With prior dependency changes, we no longer install `psycopg` onto users' computers, but the `get_random_secret_key` function used in `setup.sh` requires Django to be fully set up prior to calling the function. As such, the function errors due to the missing dependency.
Since the secret key generated here is only going to be used for development, we can simply replace it with a more straightforward `secrets.token_hex(32)`, despite its much lesser security.
=> Replace django get_random_secret_key with secrets.token_hex

csm_web/frontend/src/components/Policies.tsx, csm_web/frontend/static/frontend/data/enrollment_policies.tsx
Closes #489 
Due to the unit policy change, we need to update the policies page on Scheduler.
=> Update policies for new DeCal units

csm_web/frontend/src/components/course/SectionCard.tsx
- Modal popup redirects to profile update page
- Link to mentor profiles
=> Added UI features on section enrollment page

csm_web/scheduler/admin.py, csm_web/scheduler/views/export.py
Prior, due to traversals through many-to-many and many-to-one field relations, the counts for the number of students/mentors/sections were messed up. This has now been fixed by ensuring that the counts are for distinct objects.
The Django admin console section count has also been fixed to actually look at the number of sections, since now mentors can be associated with no section.
=> Fix queries for counts in course data export

csm_web/csm_web/settings.py
The prior integration of Python 3.12 and Django 5.x broke the build process on Heroku; this PR fixes the issues.
In the future, we should look into removing `django-heroku` entirely, since the package is deprecated. (See #518.)
=> Disable configuration of staticfiles for heroku
