csm_web/frontend/src/components/Course.js

added mailto link with mentor email under course details from mentor profile API info

mentor email on course enrollment page

---

csm_web/scheduler/factories.py
csm_web/scheduler/management/commands/createtestdata.py
setup.sh

Spent like an hour today getting JMs set up again after something happened with virtualenvs. I've refactored the setup script, made it more robust, and added additional functionality to it  in order to avoid having to do any setup manually in the future.

Improved setup

---

csm_web/frontend/src/components/App.js
csm_web/frontend/src/components/Override.js
csm_web/frontend/src/components/Section.js
csm_web/frontend/static/frontend/css/style.css
csm_web/scheduler/admin.py
csm_web/scheduler/serializers.py

Added conditional CSS class names for section summaries to make actively overridden spacetime details more apparent.

greater visibility for active override

---

csm_web/logistinator/models.py
csm_web/logistinator/serializers.py
csm_web/logistinator/urls.py
csm_web/logistinator/views.py

I added the room availabilities model.

Room Availability model added

---

csm_web/frontend/src/components/Section.js
csm_web/frontend/static/frontend/css/style.css

Added button that toggles the number of weeks shown in Scheduler

Scheduler Show More/Show Less Button

---

requirements.txt

Updating bc of a security vuln. I haven't tested this extensively (I only ran the setup script + went to a few pages on my local build), but everything seems to work, and even if it doesn't nobody cares since it's summer and we might be migrating to AWS anyway.

Up Django to 2.2

---

.gitignore
.pre-commit.sh
package-lock.json
package.json
setup.sh

Improve pre-commit hook and add it to the repo instead of it being downloaded from elsewhere

Pre-commit hook

---

.nodemon.sh
README.md
package-lock.json
package.json

Add script `npm run watch` which watches the frontend for changes and automatically rebuilds accordingly.

Automatically rebuild frontend

---

.pre-commit.sh
README.md
csm_web/scheduler/factories.py
csm_web/scheduler/models.py
requirements.txt
setup.sh

`black` produces code that is miserable to read, so we're replacing it with `autopep8`.

Replace black with autopep8

---

csm_web/scheduler/admin.py
csm_web/scheduler/models.py
csm_web/scheduler/views.py

I gave up on making spacetime creation in sections work for now, but this commit adds a bunch of qol stuff like being able to filter students on course, and making a few fields autocompletes rather than dropdowns.

Admin fixes

---

csm_web/scheduler/management/commands/export_section.py
csm_web/scheduler/management/commands/patchattendances.py

Fixed a database bug where attendances were being generated for day of the section, but the API was PUTing attendances for the start of the week.

Update attendance patcher

---

csm_web/scheduler/admin.py

Doing this manually is a pain, and a surprisingly common request.

Add admin action to swap the mentors of two sections

---

csm_web/scheduler/admin.py

Creates a custom admin form so we can actually create sections with new spacetimes.
I couldn't find an easy way to embed students as a URL (short of creating a new widget), but I think it shouldn't be too difficult to find the student through admin as a workaround.

Make spacetime on section admin editable

---

csm_web/csm_web/settings.py
csm_web/frontend/src/components/Course.js
csm_web/frontend/src/components/Home.js
csm_web/frontend/src/components/MentorSection.js
csm_web/frontend/src/components/Section.js
csm_web/frontend/src/components/StudentSection.js
csm_web/frontend/static/frontend/css/style.css
csm_web/scheduler/factories.py
csm_web/scheduler/serializers.py
csm_web/scheduler/urls.py
csm_web/scheduler/views.py

Created a frontend flow for coordinators much like how students/mentors each have a dedicated flow. I was able to reuse a lot of existing code. The following functionality has been added for Coordinators:
- "Coordinator" card on home page for course(s) they are coord for
- Ability to add sections for their course
- Edit time/location/capacity/description for any section in their course
- Add/drop students to/from any section in their course
- Edit student attendance for any section in their course
I have *deliberately* left out the ability for coordinators to set enrollment start/end times, as enrollment requires scaling our servers, I want to make sure coordinators *have* to ask tech to set this.

Coordinator Interface

---

requirements.txt

addresses dependabot alert for django

Bump Django to 3.0.7

---

.eslintignore
.github/workflows/nodejs.yml
csm_web/frontend/src/components/Home.js
csm_web/frontend/src/index.js

See #160. Still needs some configuration to get ESLint/prettier to look in the right places.
This should probably be merged before #178, given that our django tests don't really work.

Add node linter Github Action

---

README.md
csm_web/frontend/src/components/Course.js
csm_web/frontend/static/frontend/css/style.css
csm_web/scheduler/factories.py
csm_web/scheduler/management/commands/uploadsections.py
csm_web/scheduler/models.py
csm_web/scheduler/serializers.py
csm_web/scheduler/views.py

Coordinators can now easily create sections again, now with support for multiple spacetimes per section.

Restore ability for Coordinators to create sections

---

csm_web/frontend/src/components/resource_aggregation/ResourceWrapper.tsx
csm_web/frontend/src/components/resource_aggregation/Resources.tsx
csm_web/frontend/src/utils/user.tsx
csm_web/frontend/static/frontend/css/resource_aggregation.css
csm_web/frontend/static/frontend/css/style.css
csm_web/scheduler/factories.py
csm_web/scheduler/serializers.py
csm_web/scheduler/views.py
package-lock.json

Added a list of buttons above the resource table to allow switching between courses.
Modified editing behavior to only show for courses that the user has coordinator access to.

Create tabs for switching courses, modify editing behavior

---

csm_web/frontend/src/components/resource_aggregation/ResourceEdit.tsx
csm_web/frontend/src/components/resource_aggregation/ResourceWrapper.tsx
csm_web/frontend/static/frontend/css/resource_aggregation.css
csm_web/frontend/static/frontend/css/style.css
package-lock.json
package.json

Resource agg frontend

---

csm_web/frontend/src/components/resource_aggregation/ResourceRow.tsx
csm_web/frontend/src/components/resource_aggregation/ResourceWrapper.tsx
csm_web/frontend/src/components/resource_aggregation/Resources.tsx
csm_web/frontend/static/frontend/css/resource_aggregation.css
csm_web/frontend/static/frontend/css/style.css
requirements.txt

tabs and all worksheets in one cell

---

csm_web/frontend/src/components/resource_aggregation/ResourceEdit.tsx
csm_web/frontend/src/components/resource_aggregation/ResourceRow.tsx
csm_web/frontend/src/components/resource_aggregation/ResourceTable.tsx
csm_web/frontend/static/frontend/css/resource_aggregation.css
package-lock.json
package.json

Resource aggregation UI

---

csm_web/frontend/src/components/resource_aggregation/ResourceEdit.tsx
csm_web/frontend/src/components/resource_aggregation/ResourceTable.tsx
csm_web/frontend/src/components/resource_aggregation/ResourceTypes.tsx
csm_web/frontend/src/components/resource_aggregation/ResourceWorksheetEdit.tsx
csm_web/frontend/static/frontend/css/resource_aggregation.css
csm_web/scheduler/views.py

Add input validation

---

csm_web/frontend/src/components/resource_aggregation/ResourceEdit.tsx
csm_web/frontend/src/components/resource_aggregation/ResourceWorksheetEdit.tsx
csm_web/frontend/static/frontend/css/resource_aggregation.css
csm_web/frontend/static/frontend/css/style.css

Revamped the edit modal UI, with support for multiple worksheets using CSS grid.

Resource Edit UI

---

package-lock.json

Ran `npm audit fix` to fix dependabot alerts.

Update npm packages for security updates

---

csm_web/csm_web/settings.py
csm_web/frontend/src/components/Course.js
csm_web/frontend/src/components/CourseMenu.tsx
csm_web/frontend/static/frontend/css/resource_aggregation.css
package-lock.json

Several minor fixes merged into one branch for ease (first two originally were in their own branches):
- (#224) Resource tab CSS fix for longer course names; removed the fixed width but mobile wrapping is less pretty
- (#225) Dependabot fixes with `npm audit --fix`
- Add new config for the [default Django primary key](https://docs.djangoproject.com/en/3.2/topics/db/models/#automatic-primary-key-fields); this was changed in Django 3.2 and now needs a default field type.

Minor fixes

---

csm_web/scheduler/management/commands/create_attendances.py

Quick hotfix to remove postgres managers, instead manually saving objects.

Hotfix: remove postgres manager and manually create and save objects

---

csm_web/scheduler/management/commands/create_attendances.py

There were previously errors in the attendance script if there are existing attendance and section occurrence objects, and are fixed in this PR.

Resolve attendance conflicts in create attendance script

---

csm_web/scheduler/management/commands/create_attendances.py

Fixes an additional bug with presence objects causing validation errors

Hotfix attendance conflicts

---

csm_web/frontend/src/components/CourseMenu.tsx
csm_web/scheduler/serializers.py
csm_web/scheduler/urls.py
csm_web/scheduler/views/__init__.py
csm_web/scheduler/views/user.py

Added new view to get user info (in particular, the priority enrollment date), and updated the frontend UI to show the priority date if not null.

Frontend UI for priority enrollment

---

csm_web/scheduler/management/commands/create_attendances.py
csm_web/scheduler/models.py
csm_web/scheduler/serializers.py
csm_web/scheduler/views/course.py
csm_web/scheduler/views/section.py
csm_web/scheduler/views/student.py

Added fixes as described in #258.

Better timezone handling

---

.github/workflows/django.yml
csm_web/csm_web/settings.py

Similar to commit 559b70d9 but with the newly updated pytest integration.
(I'll be pushing to this branch and squashing all commits when done—it's very hard to debug github workflows)

Add Django Workflow

---

setup.sh

PR for any fixes for bugs occurring during setup for the new round of tech mentors.

Setup bugfixes

---

package-lock.json

Updating dependencies from `npm`.

Add React to package-lock

---

package-lock.json
requirements.txt

Reference dependabot PRs #294 and #295.

Merge dependabot updates

---

csm_web/scheduler/views/spacetime.py

Feat/spacetime override deletion/backend

---

csm_web/frontend/src/components/Home.tsx

Resolves #315; edited the frontend to filter for mentor profiles with an associated section.

Fix bug in displaying mentors with no sections

---

csm_web/frontend/src/components/App.tsx
csm_web/frontend/src/components/Policies.tsx
csm_web/frontend/static/frontend/css/policies.css
csm_web/frontend/static/frontend/css/style.css
csm_web/frontend/static/frontend/data/enrollment_policies.tsx

:alekk:
plz roast the code so this can 🚢 
most of the code is stolen from the previous branch feat/enrollment-policies/header but merge conflicts after not touching it for a semester are too cursed

(feat) completed enrollment policies page

---

csm_web/frontend/src/components/section/MentorSectionInfo.tsx
csm_web/frontend/src/components/section/SpacetimeDeleteModal.tsx
csm_web/frontend/src/components/section/SpacetimeEditModal.tsx
csm_web/frontend/static/frontend/css/spacetime_delete.css
csm_web/frontend/static/frontend/css/style.css
csm_web/scheduler/factories.py
csm_web/scheduler/tests/models/test_spacetime.py
csm_web/scheduler/views/spacetime.py

- Added button and popup for coordinators to delete a spacetime for a section
- Added button and popup for coordinators and mentors to delete an override for a section
- Created a new modal to verify deletion
- Added two views to spacetime.py to handle functionality
- Comprehensive tests (requiring a Coordinator Factory to be made)

Spacetime/Override Deletion

---

csm_web/frontend/src/components/resource_aggregation/ResourceEdit.tsx
csm_web/frontend/static/frontend/css/resource_aggregation.css

Coordinator Topic Delimiter Tooltip

---

package-lock.json
package.json

Bump typescript from 4.3.5 to 4.8.4

Update typescript dependency

---

.github/workflows/cypress.yml
csm_web/frontend/src/components/section/CoordinatorAddStudentModal.tsx
cypress/e2e/coordinator-course.cy.ts
cypress/e2e/login.cy.ts
cypress/tsconfig.json

Temporary branch for testing the Github Action; will squash and merge after this is finalized.
(needs to have a base of master in order for CI to run)

Add parallelization for cypress tests

---

requirements.txt

Accidentally created a new branch for other dependabot PRs, so this merges those commits into the deps/dependabot branch.

Merge deps/main into deps/dependabot

---

cypress/e2e/section/coordinator-section.cy.ts

Another flaky test due to bad chaining which prevents retries.

Fix Cypress conditions to allow retry

---

.github/workflows/cypress.yml
.github/workflows/django.yml
.github/workflows/nodejs.yml

Currently, status checks in PRs have inconsistent names; this PR serves to fix that, explicitly setting names for all GitHub actions.

Add names to GitHub actions

---

csm_web/frontend/src/components/section/SpacetimeEditModal.tsx

Fixed bug where coordinator was not able to change the day of a recurring seciton.

Fix change day for section in coord interface

---

csm_web/frontend/src/components/section/SpacetimeEditModal.tsx
csm_web/scheduler/views/matcher.py

Matcher would create multiple mentors with the same user. We turn the input list into a set so there cannot be any duplicate emails. 
https://pylint.pycqa.org/en/latest/user_guide/configuration/all-options.html more details about flags i added.

Fix multiple mentors added to matcher

---

.github/workflows/cypress.yml
package-lock.json
package.json

The Cypress Github action is a little bit outdated; this PR aims to update the workflow to ensure that we're up to date with dependencies.
This PR also updates Cypress to version 13 (the latest), as it adds additional functionality with Cypress Cloud, and also fixes some issues with the Github CI.

Update Cypress Github Action

---

package-lock.json
package.json

There are currently some issues regarding Firefox browser connectivity within Cypress, which are hopefully fixed with an updated Cypress version.

Upgrade Cypress version

---

csm_web/scheduler/models.py
csm_web/scheduler/views/waitlistedStudent.py

Refactored existing code to use the decorator and moved add student from waitlist logic into the model. Did not add tests yet. Need to add the function call to the model when a student gets dropped from a section

convert viewset, remove add from waitlist from views
